#!/bin/sh

# Format
npm run format
count=`git diff --stat | wc -l`
if [ $count -gt 0 ]; 
then
	echo 
	echo "*************************************************"
	echo   COMMIT FAILED - Formatting changes found!
	echo
	echo   Please add the formatting changes and re-commit
	echo "*************************************************"
	echo 
	exit 1
fi

# Build, lint and test
npm run checkin-validate

