[build]
  publish = "dist/apps/public-form-demo"
  command = "mkdir -p dist/apps/public-form-demo"

# Redirect all traffic to the digital service demo
[[redirects]]
  from = "/*"
  to = "https://digital-service-demo-v2.netlify.app/"
  status = 301
  force = true
