<svelte:options tag="goa-icon" />

<script lang="ts" context="module">
  export type IconSize = "small" | "medium" | "large" | "xlarge";
  export type IconVariant = "primary" | "secondary" | "tertiary";
  export type IconTheme = "outline" | "filled" | "sharp";

  export type GoAIconType =
    | "accessibility"
    | "add-circle"
    | "add"
    | "airplane"
    | "alarm"
    | "albums"
    | "alert-circle"
    | "alert"
    | "american-football"
    | "analytics"
    | "aperture"
    | "apps"
    | "archive"
    | "arrow-back-circle"
    | "arrow-back"
    | "arrow-down-circle"
    | "arrow-down"
    | "arrow-forward-circle"
    | "arrow-forward"
    | "arrow-redo-circle"
    | "arrow-redo"
    | "arrow-undo-circle"
    | "arrow-undo"
    | "arrow-up-circle"
    | "arrow-up"
    | "at-circle"
    | "at"
    | "attach"
    | "backspace"
    | "bag-add"
    | "bag-check"
    | "bag-handle"
    | "bag"
    | "bag-remove"
    | "balloon"
    | "ban"
    | "bandage"
    | "bar-chart"
    | "barbell"
    | "barcode"
    | "baseball"
    | "basket"
    | "basketball"
    | "battery-charging"
    | "battery-dead"
    | "battery-full"
    | "battery-half"
    | "beaker"
    | "bed"
    | "beer"
    | "bicycle"
    | "bluetooth"
    | "boat"
    | "body"
    | "bonfire"
    | "book"
    | "bookmark"
    | "bookmarks"
    | "bowling-ball"
    | "briefcase"
    | "browsers"
    | "brush"
    | "bug"
    | "build"
    | "bulb"
    | "bus"
    | "business"
    | "cafe"
    | "calculator"
    | "calendar-clear"
    | "calendar-number"
    | "calendar"
    | "call"
    | "camera"
    | "camera-reverse"
    | "car"
    | "car-sport"
    | "card"
    | "caret-back-circle"
    | "caret-back"
    | "caret-down-circle"
    | "caret-down"
    | "caret-forward-circle"
    | "caret-forward"
    | "caret-up-circle"
    | "caret-up"
    | "cart"
    | "cash"
    | "cellular"
    | "chatbox-ellipses"
    | "chatbox"
    | "chatbubble-ellipses"
    | "chatbubble"
    | "chatbubbles"
    | "checkbox"
    | "checkmark-circle"
    | "checkmark-done-circle"
    | "checkmark-done"
    | "checkmark"
    | "chevron-back-circle"
    | "chevron-back"
    | "chevron-down-circle"
    | "chevron-down"
    | "chevron-forward-circle"
    | "chevron-forward"
    | "chevron-up-circle"
    | "chevron-up"
    | "clipboard"
    | "close-circle"
    | "close"
    | "cloud-circle"
    | "cloud-done"
    | "cloud-download"
    | "cloud-offline"
    | "cloud"
    | "cloud-upload"
    | "cloudy-night"
    | "cloudy"
    | "code-download"
    | "code"
    | "code-slash"
    | "code-working"
    | "cog"
    | "color-fill"
    | "color-filter"
    | "color-palette"
    | "color-wand"
    | "compass"
    | "construct"
    | "contract"
    | "contrast"
    | "copy"
    | "create"
    | "crop"
    | "cube"
    | "cut"
    | "desktop"
    | "diamond"
    | "dice"
    | "disc"
    | "document-attach"
    | "document-lock"
    | "document"
    | "document-text"
    | "documents"
    | "download"
    | "duplicate"
    | "ear"
    | "earth"
    | "easel"
    | "egg"
    | "ellipse"
    | "ellipsis-horizontal-circle"
    | "ellipsis-horizontal"
    | "ellipsis-vertical-circle"
    | "ellipsis-vertical"
    | "enter"
    | "exit"
    | "expand"
    | "extension-puzzle"
    | "eye-off"
    | "eye"
    | "eyedrop"
    | "fast-food"
    | "female"
    | "file-tray-full"
    | "file-tray"
    | "file-tray-stacked"
    | "filenames.ps1"
    | "film"
    | "filter-circle"
    | "filter"
    | "finger-print"
    | "fish"
    | "fitness"
    | "flag"
    | "flame"
    | "flash-off"
    | "flash"
    | "flashlight"
    | "flask"
    | "flower"
    | "folder-open"
    | "folder"
    | "football"
    | "footsteps"
    | "funnel"
    | "game-controller"
    | "gift"
    | "git-branch"
    | "git-commit"
    | "git-compare"
    | "git-merge"
    | "git-network"
    | "git-pull-request"
    | "glasses"
    | "globe"
    | "golf"
    | "grid"
    | "hammer"
    | "hand-left"
    | "hand-right"
    | "happy"
    | "hardware-chip"
    | "headset"
    | "heart-circle"
    | "heart-dislike-circle"
    | "heart-dislike"
    | "heart-half"
    | "heart"
    | "help-buoy"
    | "help-circle"
    | "help"
    | "home"
    | "hourglass"
    | "ice-cream"
    | "id-card"
    | "image"
    | "images"
    | "infinite"
    | "information-circle"
    | "information"
    | "invert-mode"
    | "journal"
    | "key"
    | "keypad"
    | "language"
    | "laptop"
    | "layers"
    | "leaf"
    | "library"
    | "link"
    | "list-circle"
    | "list"
    | "locate"
    | "location"
    | "lock-closed"
    | "lock-open"
    | "log-in"
    | "log-out"
    | "magnet"
    | "mail-open"
    | "mail"
    | "mail-unread"
    | "male-female"
    | "male"
    | "man"
    | "map"
    | "medal"
    | "medical"
    | "medkit"
    | "megaphone"
    | "menu"
    | "mic-circle"
    | "mic-off-circle"
    | "mic-off"
    | "mic"
    | "moon"
    | "move"
    | "musical-note"
    | "musical-notes"
    | "navigate-circle"
    | "navigate"
    | "newspaper"
    | "notifications-circle"
    | "notifications-off-circle"
    | "notifications-off"
    | "notifications"
    | "nuclear"
    | "nutrition"
    | "open"
    | "options"
    | "paper-plane"
    | "partly-sunny"
    | "pause-circle"
    | "pause"
    | "paw"
    | "pencil"
    | "people-circle"
    | "people"
    | "person-add"
    | "person-circle"
    | "person"
    | "person-remove"
    | "phone-landscape"
    | "phone-portrait"
    | "pie-chart"
    | "pin"
    | "pint"
    | "pizza"
    | "planet"
    | "play-back-circle"
    | "play-back"
    | "play-circle"
    | "play-forward-circle"
    | "play-forward"
    | "play"
    | "play-skip-back-circle"
    | "play-skip-back"
    | "play-skip-forward-circle"
    | "play-skip-forward"
    | "podium"
    | "power"
    | "pricetag"
    | "pricetags"
    | "print"
    | "prism"
    | "pulse"
    | "push"
    | "qr-code"
    | "radio-button-off"
    | "radio-button-on"
    | "radio"
    | "rainy"
    | "reader"
    | "receipt"
    | "recording"
    | "refresh-circle"
    | "refresh"
    | "reload-circle"
    | "reload"
    | "remove-circle"
    | "remove"
    | "reorder-four"
    | "reorder-three"
    | "reorder-two"
    | "repeat"
    | "resize"
    | "restaurant"
    | "return-down-back"
    | "return-down-forward"
    | "return-up-back"
    | "return-up-forward"
    | "ribbon"
    | "rocket"
    | "rose"
    | "sad"
    | "save"
    | "scale"
    | "scan-circle"
    | "scan"
    | "school"
    | "search-circle"
    | "search"
    | "send"
    | "server"
    | "settings"
    | "shapes"
    | "share"
    | "share-social"
    | "shield-checkmark"
    | "shield-half"
    | "shield"
    | "shirt"
    | "shuffle"
    | "skull"
    | "snow"
    | "sparkles"
    | "speedometer"
    | "square"
    | "star-half"
    | "star"
    | "stats-chart"
    | "stop-circle"
    | "stop"
    | "stopwatch"
    | "storefront"
    | "subway"
    | "sunny"
    | "swap-horizontal"
    | "swap-vertical"
    | "sync-circle"
    | "sync"
    | "tablet-landscape"
    | "tablet-portrait"
    | "telescope"
    | "tennisball"
    | "terminal"
    | "text"
    | "thermometer"
    | "thumbs-down"
    | "thumbs-up"
    | "thunderstorm"
    | "ticket"
    | "time"
    | "timer"
    | "today"
    | "toggle"
    | "trail-sign"
    | "train"
    | "transgender"
    | "trash-bin"
    | "trash"
    | "trending-down"
    | "trending-up"
    | "triangle"
    | "trophy"
    | "tv"
    | "umbrella"
    | "unlink"
    | "videocam-off"
    | "videocam"
    | "volume-high"
    | "volume-low"
    | "volume-medium"
    | "volume-mute"
    | "volume-off"
    | "walk"
    | "wallet"
    | "warning"
    | "watch"
    | "water"
    | "wifi"
    | "wine"
    | "woman"
    | "logo-alipay"
    | "logo-amazon"
    | "logo-amplify"
    | "logo-android"
    | "logo-angular"
    | "logo-apple"
    | "logo-apple-appstore"
    | "logo-apple-ar"
    | "logo-behance"
    | "logo-bitbucket"
    | "logo-bitcoin"
    | "logo-buffer"
    | "logo-capacitor"
    | "logo-chrome"
    | "logo-closed-captioning"
    | "logo-codepen"
    | "logo-css3"
    | "logo-designernews"
    | "logo-deviantart"
    | "logo-discord"
    | "logo-docker"
    | "logo-dribbble"
    | "logo-dropbox"
    | "logo-edge"
    | "logo-electron"
    | "logo-euro"
    | "logo-facebook"
    | "logo-figma"
    | "logo-firebase"
    | "logo-firefox"
    | "logo-flickr"
    | "logo-foursquare"
    | "logo-github"
    | "logo-gitlab"
    | "logo-google"
    | "logo-google-playstore"
    | "logo-hackernews"
    | "logo-html5"
    | "logo-instagram"
    | "logo-ionic"
    | "logo-ionitron"
    | "logo-javascript"
    | "logo-laravel"
    | "logo-linkedin"
    | "logo-markdown"
    | "logo-mastodon"
    | "logo-medium"
    | "logo-microsoft"
    | "logo-no-smoking"
    | "logo-nodejs"
    | "logo-npm"
    | "logo-octocat"
    | "logo-paypal"
    | "logo-pinterest"
    | "logo-playstation"
    | "logo-pwa"
    | "logo-python"
    | "logo-react"
    | "logo-reddit"
    | "logo-rss"
    | "logo-sass"
    | "logo-skype"
    | "logo-slack"
    | "logo-snapchat"
    | "logo-soundcloud"
    | "logo-stackoverflow"
    | "logo-steam"
    | "logo-stencil"
    | "logo-tableau"
    | "logo-tiktok"
    | "logo-tumblr"
    | "logo-tux"
    | "logo-twitch"
    | "logo-twitter"
    | "logo-usd"
    | "logo-venmo"
    | "logo-vercel"
    | "logo-vimeo"
    | "logo-vk"
    | "logo-vue"
    | "logo-web-component"
    | "logo-wechat"
    | "logo-whatsapp"
    | "logo-windows"
    | "logo-wordpress"
    | "logo-xbox"
    | "logo-xing"
    | "logo-yahoo"
    | "logo-yen"
    | "logo-youtube";
</script>

<script lang="ts">
  import { toBoolean } from "../../common/utils";
  import type { Spacing } from "../../common/styling";
  import { calculateMargin } from "../../common/styling";

  // margin
  export let mt: Spacing = null;
  export let mr: Spacing = null;
  export let mb: Spacing = null;
  export let ml: Spacing = null;

  // required
  export let type: GoAIconType;

  // optional
  export let size: IconSize = "medium";
  export let theme: IconTheme = "outline";
  export let inverted: string = "false";
  export let fillcolor: string = "";
  export let opacity: number = 1;
  export let title: string = "";
  export let testid: string = "";

  // Private
  const _iconOverrides = {
    pencil: `<svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M16.1442 5.47956L12.5355 1.87088L13.7196 0.686776C14.0391 0.367257 14.4385 0.212197 14.9178 0.221594C15.3971 0.230992 15.7965 0.39545 16.116 0.714969L17.3283 1.92726C17.6478 2.24678 17.8076 2.64148 17.8076 3.11136C17.8076 3.58124 17.6478 3.97594 17.3283 4.29546L16.1442 5.47956ZM1.03951 17.8424C0.795173 17.8424 0.593125 17.7626 0.433365 17.6028C0.273605 17.443 0.193726 17.241 0.193726 16.9966V14.5721C0.193726 14.4593 0.212521 14.356 0.250112 14.262C0.287702 14.168 0.353485 14.074 0.447461 13.9801L11.4689 2.93435L15.0776 6.54303L4.05615 17.5887C3.96217 17.6827 3.8682 17.7485 3.77422 17.7861C3.68024 17.8236 3.57687 17.8424 3.4641 17.8424H1.03951Z" fill="#333333"/>
</svg>`,
    checkmark: `<svg width="18" height="14" viewBox="0 0 18 14" fill="none" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" clip-rule="evenodd" d="M6.20129 11.5368L15.9974 0.341265C16.3611 -0.0743717 16.9929 -0.116489 17.4085 0.247193C17.8241 0.610875 17.8663 1.24264 17.5026 1.65827L7.00258 13.6583C6.82032 13.8666 6.5599 13.99 6.28328 13.9992C6.00666 14.0084 5.7386 13.9026 5.54289 13.7069L1.04289 9.20688C0.652369 8.81635 0.652369 8.18319 1.04289 7.79266C1.43342 7.40214 2.06658 7.40214 2.45711 7.79266L6.20129 11.5368Z" fill="#333333"/>
</svg>`,
    remove: `<svg width="16" height="20" viewBox="0 0 16 1" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M1.5 -0.000244141C0.947715 -0.000244141 0.5 0.447471 0.5 0.999756C0.5 1.55204 0.947715 1.99976 1.5 1.99976H15C15.5523 1.99976 16 1.55204 16 0.999756C16 0.447471 15.5523 -0.000244141 15 -0.000244141H1.5Z" fill="#333333"/>
</svg>`,
  }

  $: isInverted = toBoolean(inverted);

  $: _size = {
    small: "1.25rem",
    medium: "1.5rem",
    large: "2rem",
  }[size];
</script>

<div
  class="goa-icon"
  class:inverted={isInverted}
  data-testid={testid}
  {title}
  style={`
    ${calculateMargin(mt, mr, mb, ml)}
    --size: ${_size};
    --fill-color: ${fillcolor};
    --opacity: ${opacity};
  `}
>
  {#if type}
    {#if Object.keys(_iconOverrides).includes(type)}
      <div class="icon-override">
        {@html _iconOverrides[type]}
        <span />
      </div>
    {:else}
      <ion-icon
        name={theme === "filled" || type.indexOf("logo") === 0 ? type : `${type}-${theme}`}
      />
    {/if}
  {/if}
</div>

<style>
  :host {
    display: inline-flex;
    align-items: center;
  }

  ion-icon {
    pointer-events: none;
    width: 100%;
    height: 100%;
  }

  .goa-icon {
    width: var(--size);
    height: var(--size);
    fill: var(--fill-color);
    color: var(--fill-color);
    opacity: var(--opacity);
    display: inline-flex;
    align-items: center;
    justify-content: center;
  }

  .icon-override {
    display: flex;
    flex-direction: column;
    align-items: center;
  }

  .inverted * {
    color: #fff;
    fill: #fff;
  }
</style>
