export type Code = { code: string; name: string };

export const Countries: Code[] = [
  { code: "", name: "" },
  { code: "AW", name: "Aruba" },
  { code: "AF", name: "Afghanistan" },
  { code: "AO", name: "Angola" },
  { code: "AI", name: "Anguilla" },
  { code: "AX", name: "Åland Islands" },
  { code: "AL", name: "Albania" },
  { code: "DZ", name: "Algeria" },
  { code: "AD", name: "Andorra" },
  { code: "AR", name: "Argentina" },
  { code: "AM", name: "Armenia" },
  { code: "AS", name: "American Samoa" },
  { code: "AQ", name: "Antarctica" },
  { code: "AG", name: "Antigua and Barbuda" },
  { code: "AU", name: "Australia" },
  { code: "AT", name: "Austria" },
  { code: "AZ", name: "Azerbaijan" },
  { code: "BI", name: "Burundi" },
  { code: "BE", name: "Belgium" },
  { code: "BJ", name: "Benin" },
  { code: "BQ", name: "Bonaire, Sint Eustatius and Saba" },
  { code: "BF", name: "Burkina Faso" },
  { code: "BD", name: "Bangladesh" },
  { code: "BG", name: "Bulgaria" },
  { code: "BH", name: "Bahrain" },
  { code: "BS", name: "Bahamas" },
  { code: "BA", name: "Bosnia and Herzegovina" },
  { code: "BY", name: "Belarus" },
  { code: "BZ", name: "Belize" },
  { code: "BM", name: "Bermuda" },
  { code: "BO", name: "Bolivia, Plurinational State of" },
  { code: "BR", name: "Brazil" },
  { code: "BB", name: "Barbados" },
  { code: "BN", name: "Brunei Darussalam" },
  { code: "BT", name: "Bhutan" },
  { code: "BV", name: "Bouvet Island" },
  { code: "BW", name: "Botswana" },
  { code: "IO", name: "British Indian Ocean Territory" },
  { code: "CF", name: "Central African Republic" },
  { code: "CA", name: "Canada" },
  { code: "CC", name: "Cocos (Keeling) Islands" },
  { code: "CL", name: "Chile" },
  { code: "CN", name: "China" },
  { code: "CI", name: "Côte d'Ivoire" },
  { code: "CM", name: "Cameroon" },
  { code: "CD", name: "Congo, The Democratic Republic of the" },
  { code: "CG", name: "Congo" },
  { code: "CK", name: "Cook Islands" },
  { code: "CO", name: "Colombia" },
  { code: "KM", name: "Comoros" },
  { code: "KH", name: "Cambodia" },
  { code: "CV", name: "Cabo Verde" },
  { code: "TD", name: "Chad" },
  { code: "CR", name: "Costa Rica" },
  { code: "CU", name: "Cuba" },
  { code: "CW", name: "Curaçao" },
  { code: "CX", name: "Christmas Island" },
  { code: "KY", name: "Cayman Islands" },
  { code: "HR", name: "Croatia" },
  { code: "CY", name: "Cyprus" },
  { code: "CZ", name: "Czechia" },
  { code: "DJ", name: "Djibouti" },
  { code: "DM", name: "Dominica" },
  { code: "DK", name: "Denmark" },
  { code: "DO", name: "Dominican Republic" },
  { code: "EC", name: "Ecuador" },
  { code: "EG", name: "Egypt" },
  { code: "SV", name: "El Salvador" },
  { code: "ER", name: "Eritrea" },
  { code: "SZ", name: "Eswatini" },
  { code: "EE", name: "Estonia" },
  { code: "ET", name: "Ethiopia" },
  { code: "FI", name: "Finland" },
  { code: "FJ", name: "Fiji" },
  { code: "FK", name: "Falkland Islands (Malvinas)" },
  { code: "FR", name: "France" },
  { code: "FO", name: "Faroe Islands" },
  { code: "GF", name: "French Guiana" },
  { code: "TF", name: "French Southern Territories" },
  { code: "GA", name: "Gabon" },
  { code: "GE", name: "Georgia" },
  { code: "DE", name: "Germany" },
  { code: "GG", name: "Guernsey" },
  { code: "GH", name: "Ghana" },
  { code: "GI", name: "Gibraltar" },
  { code: "GN", name: "Guinea" },
  { code: "GP", name: "Guadeloupe" },
  { code: "GM", name: "Gambia" },
  { code: "GW", name: "Guinea-Bissau" },
  { code: "GQ", name: "Equatorial Guinea" },
  { code: "GR", name: "Greece" },
  { code: "GD", name: "Grenada" },
  { code: "GL", name: "Greenland" },
  { code: "GT", name: "Guatemala" },
  { code: "GU", name: "Guam" },
  { code: "GY", name: "Guyana" },
  { code: "HK", name: "Hong Kong" },
  { code: "HM", name: "Heard Island and McDonald Islands" },
  { code: "HN", name: "Honduras" },
  { code: "VA", name: "Holy See (Vatican City State)" },
  { code: "HT", name: "Haiti" },
  { code: "HU", name: "Hungary" },
  { code: "ID", name: "Indonesia" },
  { code: "IM", name: "Isle of Man" },
  { code: "IN", name: "India" },
  { code: "IE", name: "Ireland" },
  { code: "IR", name: "Iran, Islamic Republic of" },
  { code: "IQ", name: "Iraq" },
  { code: "IS", name: "Iceland" },
  { code: "IL", name: "Israel" },
  { code: "IT", name: "Italy" },
  { code: "JM", name: "Jamaica" },
  { code: "JE", name: "Jersey" },
  { code: "JO", name: "Jordan" },
  { code: "JP", name: "Japan" },
  { code: "KZ", name: "Kazakhstan" },
  { code: "KE", name: "Kenya" },
  { code: "KG", name: "Kyrgyzstan" },
  { code: "KI", name: "Kiribati" },
  { code: "KR", name: "Korea, Republic of" },
  { code: "KW", name: "Kuwait" },
  { code: "LA", name: "Lao People's Democratic Republic" },
  { code: "LB", name: "Lebanon" },
  { code: "LR", name: "Liberia" },
  { code: "LY", name: "Libya" },
  { code: "LI", name: "Liechtenstein" },
  { code: "LS", name: "Lesotho" },
  { code: "LT", name: "Lithuania" },
  { code: "LU", name: "Luxembourg" },
  { code: "LV", name: "Latvia" },
  { code: "MO", name: "Macao" },
  { code: "MA", name: "Morocco" },
  { code: "MC", name: "Monaco" },
  { code: "MD", name: "Moldova, Republic of" },
  { code: "MG", name: "Madagascar" },
  { code: "MV", name: "Maldives" },
  { code: "MX", name: "Mexico" },
  { code: "MH", name: "Marshall Islands" },
  { code: "MK", name: "North Macedonia" },
  { code: "ML", name: "Mali" },
  { code: "MT", name: "Malta" },
  { code: "MM", name: "Myanmar" },
  { code: "ME", name: "Montenegro" },
  { code: "MN", name: "Mongolia" },
  { code: "FM", name: "Micronesia, Federated States of" },
  { code: "MZ", name: "Mozambique" },
  { code: "MR", name: "Mauritania" },
  { code: "MS", name: "Montserrat" },
  { code: "MQ", name: "Martinique" },
  { code: "MU", name: "Mauritius" },
  { code: "MW", name: "Malawi" },
  { code: "MY", name: "Malaysia" },
  { code: "YT", name: "Mayotte" },
  { code: "NA", name: "Namibia" },
  { code: "NC", name: "New Caledonia" },
  { code: "NE", name: "Niger" },
  { code: "NF", name: "Norfolk Island" },
  { code: "NG", name: "Nigeria" },
  { code: "NI", name: "Nicaragua" },
  { code: "NU", name: "Niue" },
  { code: "NL", name: "Netherlands" },
  { code: "NO", name: "Norway" },
  { code: "NP", name: "Nepal" },
  { code: "NR", name: "Nauru" },
  { code: "NZ", name: "New Zealand" },
  { code: "MP", name: "Northern Mariana Islands" },
  { code: "OM", name: "Oman" },
  { code: "PK", name: "Pakistan" },
  { code: "PA", name: "Panama" },
  { code: "PN", name: "Pitcairn" },
  { code: "PE", name: "Peru" },
  { code: "PH", name: "Philippines" },
  { code: "PW", name: "Palau" },
  { code: "PG", name: "Papua New Guinea" },
  { code: "PL", name: "Poland" },
  { code: "PR", name: "Puerto Rico" },
  { code: "KP", name: "Korea, Democratic People's Republic of" },
  { code: "PT", name: "Portugal" },
  { code: "PY", name: "Paraguay" },
  { code: "PS", name: "Palestine, State of" },
  { code: "PF", name: "French Polynesia" },
  { code: "QA", name: "Qatar" },
  { code: "RE", name: "Réunion" },
  { code: "RO", name: "Romania" },
  { code: "RU", name: "Russian Federation" },
  { code: "RW", name: "Rwanda" },
  { code: "MF", name: "Saint Martin (French part)" },
  { code: "BL", name: "Saint Barthélemy" },
  { code: "KN", name: "Saint Kitts and Nevis" },
  { code: "LC", name: "Saint Lucia" },
  { code: "SA", name: "Saudi Arabia" },
  { code: "SD", name: "Sudan" },
  { code: "SN", name: "Senegal" },
  { code: "SG", name: "Singapore" },
  { code: "GS", name: "South Georgia and the South Sandwich Islands" },
  { code: "SH", name: "Saint Helena, Ascension and Tristan da Cunha" },
  { code: "ES", name: "Spain" },
  { code: "LK", name: "Sri Lanka" },
  { code: "SJ", name: "Svalbard and Jan Mayen" },
  { code: "SB", name: "Solomon Islands" },
  { code: "SL", name: "Sierra Leone" },
  { code: "SM", name: "San Marino" },
  { code: "SO", name: "Somalia" },
  { code: "PM", name: "Saint Pierre and Miquelon" },
  { code: "RS", name: "Serbia" },
  { code: "SS", name: "South Sudan" },
  { code: "ZA", name: "South Africa" },
  { code: "ST", name: "Sao Tome and Principe" },
  { code: "WS", name: "Samoa" },
  { code: "SR", name: "Suriname" },
  { code: "SK", name: "Slovakia" },
  { code: "SI", name: "Slovenia" },
  { code: "SE", name: "Sweden" },
  { code: "CH", name: "Switzerland" },
  { code: "SX", name: "Sint Maarten (Dutch part)" },
  { code: "SC", name: "Seychelles" },
  { code: "SY", name: "Syrian Arab Republic" },
  { code: "VC", name: "Saint Vincent and the Grenadines" },
  { code: "TC", name: "Turks and Caicos Islands" },
  { code: "TG", name: "Togo" },
  { code: "TH", name: "Thailand" },
  { code: "TJ", name: "Tajikistan" },
  { code: "TK", name: "Tokelau" },
  { code: "TM", name: "Turkmenistan" },
  { code: "TL", name: "Timor-Leste" },
  { code: "TO", name: "Tonga" },
  { code: "TT", name: "Trinidad and Tobago" },
  { code: "TN", name: "Tunisia" },
  { code: "TR", name: "Turkey" },
  { code: "TV", name: "Tuvalu" },
  { code: "TW", name: "Taiwan, Province of China" },
  { code: "TZ", name: "Tanzania, United Republic of" },
  { code: "UG", name: "Uganda" },
  { code: "UA", name: "Ukraine" },
  { code: "AE", name: "United Arab Emirates" },
  { code: "UM", name: "United States Minor Outlying Islands" },
  { code: "US", name: "United States" },
  { code: "GB", name: "United Kingdom" },
  { code: "UY", name: "Uruguay" },
  { code: "UZ", name: "Uzbekistan" },
  { code: "VE", name: "Venezuela, Bolivarian Republic of" },
  { code: "VG", name: "Virgin Islands, British" },
  { code: "VI", name: "Virgin Islands, U.S." },
  { code: "VN", name: "Viet Nam" },
  { code: "VU", name: "Vanuatu" },
  { code: "WF", name: "Wallis and Futuna" },
  { code: "EH", name: "Western Sahara" },
  { code: "YE", name: "Yemen" },
  { code: "ZM", name: "Zambia" },
  { code: "ZW", name: "Zimbabwe" },
];

export const CountrySubdivisions: { [code: string]: Code[] } = {
  "CA": [
    { code: "CA-AB", name: "Alberta" },
    { code: "CA-BC", name: "British Columbia" },
    { code: "CA-MB", name: "Manitoba" },
    { code: "CA-NB", name: "New Brunswick" },
    { code: "CA-NL", name: "Newfoundland and Labrador" },
    { code: "CA-NS", name: "Nova Scotia" },
    { code: "CA-ON", name: "Ontario" },
    { code: "CA-PE", name: "Prince Edward Island" },
    { code: "CA-QC", name: "Quebec" },
    { code: "CA-SK", name: "Saskatchewan" },
    { code: "CA-NT", name: "Northwest Territories" },
    { code: "CA-NU", name: "Nunavut" },
    { code: "CA-YT", name: "Yukon" }
  ],
  "US": [
    { code: "US-AK", name: "Alaska" },
    { code: "US-AL", name: "Alabama" },
    { code: "US-AR", name: "Arkansas" },
    { code: "US-AS", name: "American Samoa" },
    { code: "US-AZ", name: "Arizona" },
    { code: "US-CA", name: "California" },
    { code: "US-CO", name: "Colorado" },
    { code: "US-CT", name: "Connecticut" },
    { code: "US-DC", name: "District of Columbia" },
    { code: "US-DE", name: "Delaware" },
    { code: "US-FL", name: "Florida" },
    { code: "US-GA", name: "Georgia" },
    { code: "US-GU", name: "Guam" },
    { code: "US-HI", name: "Hawaii" },
    { code: "US-IA", name: "Iowa" },
    { code: "US-ID", name: "Idaho" },
    { code: "US-IL", name: "Illinois" },
    { code: "US-IN", name: "Indiana" },
    { code: "US-KS", name: "Kansas" },
    { code: "US-KY", name: "Kentucky" },
    { code: "US-LA", name: "Louisiana" },
    { code: "US-MA", name: "Massachusetts" },
    { code: "US-MD", name: "Maryland" },
    { code: "US-ME", name: "Maine" },
    { code: "US-MI", name: "Michigan" },
    { code: "US-MN", name: "Minnesota" },
    { code: "US-MO", name: "Missouri" },
    { code: "US-MP", name: "Northern Mariana Islands" },
    { code: "US-MS", name: "Mississippi" },
    { code: "US-MT", name: "Montana" },
    { code: "US-NC", name: "North Carolina" },
    { code: "US-ND", name: "North Dakota" },
    { code: "US-NE", name: "Nebraska" },
    { code: "US-NH", name: "New Hampshire" },
    { code: "US-NJ", name: "New Jersey" },
    { code: "US-NM", name: "New Mexico" },
    { code: "US-NV", name: "Nevada" },
    { code: "US-NY", name: "New York" },
    { code: "US-OH", name: "Ohio" },
    { code: "US-OK", name: "Oklahoma" },
    { code: "US-OR", name: "Oregon" },
    { code: "US-PA", name: "Pennsylvania" },
    { code: "US-PR", name: "Puerto Rico" },
    { code: "US-RI", name: "Rhode Island" },
    { code: "US-SC", name: "South Carolina" },
    { code: "US-SD", name: "South Dakota" },
    { code: "US-TN", name: "Tennessee" },
    { code: "US-TX", name: "Texas" },
    { code: "US-UM", name: "United States Minor Outlying Islands" },
    { code: "US-UT", name: "Utah" },
    { code: "US-VA", name: "Virginia" },
    { code: "US-VI", name: "Virgin Islands, U.S." },
    { code: "US-VT", name: "Vermont" },
    { code: "US-WA", name: "Washington" },
    { code: "US-WI", name: "Wisconsin" },
    { code: "US-WV", name: "West Virginia" },
    { code: "US-WY", name: "Wyoming" }
  ],
};
