name: Bug report 🐞
description: >-
  Something is broken and you have a reliable reproduction? Let us know here.
  For questions, please use "Question" below.
title: ""
type: "Bug"
projects: ["GovAlta/35"]
body:
  - type: markdown
    attributes:
      value: >-
        Please make sure you're using the latest version of either
        [Angular Components](https://www.npmjs.com/package/@abgov/angular-components) or
        [React Components](https://www.npmjs.com/package/@abgov/react-components) and
        [Web Components](https://www.npmjs.com/package/@abgov/web-components).
  - type: input
    id: email
    attributes:
      label: Your email
      placeholder: ex. firstname.lastname@gov.ab.ca
    validations:
      required: true
  - type: input
    id: web-version
    attributes:
      label: Web components version
      description: The version of @abgov/web-components you have installed
    validations:
      required: true
  - type: input
    id: package-version
    attributes:
      label: React or Angular components version
      description: The version of either @abgov/react-components or @abgov/angular-components you have installed
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behaviour
      description: What do you expect to have happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behaviour
      description: What is actually happening?
    validations:
      required: true
  - type: textarea
    id: replication
    attributes:
      label: Replication Steps
      description: >-
        In numbered order, please provide the steps to see the bug
    validations:
      required: true
  - type: input
    id: stackblitz
    attributes:
      label: Stackblitz URL
      description: Share your code with us in an isolated environment
      placeholder: We prioritize issues with code provided
  - type: input
    id: jamdev
    attributes:
      label: Jam.dev URL
      description: Show us a demo of the bug
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
