name: Feature request 💡
description: Suggest an idea for this project
title: ""
type: "Feature"
projects: ["GovAlta/35"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? Please describe
      description: A clear and concise description of the problem.
  - type: textarea
    id: describe
    attributes:
      label: Describe the solution you'd like
      description: What would you like to see added to solve this problem?
    validations:
      required: true
  - type: textarea
    id: evidence
    attributes:
      label: Provide evidence this is a needed component
      description: >-
        Evidence that it's needed across multiple services. Evidence that this meets the
        needs of the users of those services.
      placeholder: The more evidence you can provide, the higher priority this gets
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Any alternative solutions or features you've considered.
  - type: dropdown
    id: already_created
    attributes:
      label: Do you have anything already created for this that we can use?
      options:
        - "no"
        - "yes"
  - type: dropdown
    id: currently_using
    attributes:
      label: Are you currently using this proposal inside your own service
      options:
        - "no"
        - "yes"
  - type: dropdown
    id: help
    attributes:
      label: Are you able to assist to bring the feature to reality?
      options:
        - "no"
        - "yes"
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
