import * as CommonTypes from "@abgov/ui-components-common";

export interface Margins {
  mt?: Spacing;
  mr?: Spacing;
  mb?: Spacing;
  ml?: Spacing;
}

export type Spacing = CommonTypes.Spacing;
export type GoabDropdownOnChangeDetail = CommonTypes.GoabDropdownOnChangeDetail;
export type GoabSpinnerType = CommonTypes.GoabSpinnerType;
export type GoabSpinnerSize = CommonTypes.GoabSpinnerSize;
export type GoabRadioGroupOnChangeDetail = CommonTypes.GoabRadioGroupOnChangeDetail;
export type GoabInputAutoCapitalize = CommonTypes.GoabInputAutoCapitalize;
export type GoabFormStepperOnChangeDetail = CommonTypes.GoabFormStepperOnChangeDetail;
export type GoabFileUploadInputOnSelectFileDetail =
  CommonTypes.GoabFileUploadInputOnSelectFileDetail;
export type GoabFileUploadOnCancelDetail = CommonTypes.GoabFileUploadOnCancelDetail;
export type GoabFileUploadOnDeleteDetail = CommonTypes.GoabFileUploadOnDeleteDetail;
export type GoabDropdownItemMountType = CommonTypes.GoabDropdownItemMountType;
export type GoabDatePickerOnChangeDetail = CommonTypes.GoabDatePickerOnChangeDetail;
export type GoabChipVariant = CommonTypes.GoabChipVariant;
export type GoabChipTheme = CommonTypes.GoabChipTheme;
export type GoabFilterChipTheme = CommonTypes.GoabFilterChipTheme;
export type GoabCheckboxOnChangeDetail = CommonTypes.GoabCheckboxOnChangeDetail;
export type GoabCalendarOnChangeDetail = CommonTypes.GoabCalendarOnChangeDetail;
export type GoabBadgeType = CommonTypes.GoabBadgeType;
export type GoabPaginationVariant = CommonTypes.GoabPaginationVariant;
export type GoabPaginationOnChangeDetail = CommonTypes.GoabPaginationOnChangeDetail;
export type GoabFormStepperType = CommonTypes.GoabFormStepperType;
export type GoabFormStepStatus = CommonTypes.GoabFormStepStatus;
export type GoabFormItemLabelSize = CommonTypes.GoabFormItemLabelSize;
export type GoabFormItemRequirement = CommonTypes.GoabFormItemRequirement;
export type GoabFileUploadInputVariant = CommonTypes.GoabFileUploadInputVariant;
export type GoabContainerAccent = CommonTypes.GoabContainerAccent;
export type GoabContainerPadding = CommonTypes.GoabContainerPadding;
export type GoabContainerType = CommonTypes.GoabContainerType;
export type GoabContainerWidth = CommonTypes.GoabContainerWidth;
export type GoabCalloutType = CommonTypes.GoabCalloutType;
export type GoabCalloutSize = CommonTypes.GoabCalloutSize;
export type GoabCalloutAriaLive = CommonTypes.GoabCalloutAriaLive;
export type GoabCalloutIconTheme = CommonTypes.GoabCalloutIconTheme;
export type GoabButtonType = CommonTypes.GoabButtonType;
export type GoabButtonSize = CommonTypes.GoabButtonSize;
export type GoabButtonVariant = CommonTypes.GoabButtonVariant;
export type GoabButtonGroupAlignment = CommonTypes.GoabButtonGroupAlignment;
export type GoabButtonGroupGap = CommonTypes.GoabButtonGroupGap;
export type GoabAccordionHeadingSize = CommonTypes.GoabAccordionHeadingSize;
export type GoabAccordionIconPosition = CommonTypes.GoabAccordionIconPosition;
export type GoabTooltipPosition = CommonTypes.GoabTooltipPosition;
export type GoabTooltipHorizontalAlignment = CommonTypes.GoabTooltipHorizontalAlignment;
export type GoabTextAreaCountBy = CommonTypes.GoabTextAreaCountBy;
export type GoabTextAreaOnChangeDetail = CommonTypes.GoabTextAreaOnChangeDetail;
export type GoabTextAreaOnKeyPressDetail = CommonTypes.GoabTextAreaOnKeyPressDetail;
export type GoabTabsOnChangeDetail = CommonTypes.GoabTabsOnChangeDetail;
export type GoabTableVariant = CommonTypes.GoabTableVariant;
export type GoabTableSortDirection = CommonTypes.GoabTableSortDirection;
export type GoabTableOnSortDetail = CommonTypes.GoabTableOnSortDetail;
export type GoabSpacerHorizontalSpacing = CommonTypes.GoabSpacerHorizontalSpacing;
export type GoabSpacerVerticalSpacing = CommonTypes.GoabSpacerVerticalSpacing;
export type GoabSkeletonType = CommonTypes.GoabSkeletonType;
export type GoabSkeletonSize = CommonTypes.GoabSkeletonSize;
export type GoabRadioGroupOrientation = CommonTypes.GoabRadioGroupOrientation;
export type GoabCircularProgressVariant = CommonTypes.GoabCircularProgressVariant;
export type GoabCircularProgressSize = CommonTypes.GoabCircularProgressSize;
export type GoabPopoverPosition = CommonTypes.GoabPopoverPosition;
export type GoabNotificationType = CommonTypes.GoabNotificationType;
export type GoabAriaLiveType = CommonTypes.GoabAriaLiveType;
export type GoabServiceLevel = CommonTypes.GoabServiceLevel;
export type GoabLinkTarget = CommonTypes.GoabLinkTarget;
export type GoabModalRole = CommonTypes.GoabModalRole;
export type GoabModalTransition = CommonTypes.GoabModalTransition;
export type GoabModalCalloutVariant = CommonTypes.GoabModalCalloutVariant;
export type GoabDate = CommonTypes.GoabDate;
export type GoabInputType = CommonTypes.GoabInputType;
export type GoabAutoCapitalize = CommonTypes.GoabAutoCapitalize;
export type GoabIconFilledType = CommonTypes.GoabIconFilledType;
export type GoabIconType = CommonTypes.GoabIconType;
export type GoabIconSize = CommonTypes.GoabIconSize;
export type GoabIconTheme = CommonTypes.GoabIconTheme;
export type GoabIconButtonVariant = CommonTypes.GoabIconButtonVariant;
export type GoabIconVariant = CommonTypes.GoabIconVariant;
export type NumericSpacing = CommonTypes.NumericSpacing;
export type TShirtSpacing = CommonTypes.TShirtSpacing;
export type GoabBlockDirection = CommonTypes.GoabBlockDirection;
export type GoabBlockAlignment = CommonTypes.GoabBlockAlignment;
export type GoabLinkButtonType = CommonTypes.GoabLinkButtonType;
export type GoabTextMaxWidth = CommonTypes.GoabTextMaxWidth;
export type GoabTextHeadingElement = CommonTypes.GoabTextHeadingElement;
export type GoabTextTextElement = CommonTypes.GoabTextTextElement;
export type GoabTextHeadingSize = CommonTypes.GoabTextHeadingSize;
export type GoabTextBodySize = CommonTypes.GoabTextBodySize;
export type GoabTextSize = CommonTypes.GoabTextSize;
export type GoabTextColor = CommonTypes.GoabTextColor;
export type GoabFielsetOnContinueDetail = CommonTypes.GoabFielsetOnContinueDetail;
export type GoabFormField = CommonTypes.GoabFormField;
export type GoabFormState = CommonTypes.GoabFormState;
export type GoabFormStorageType = CommonTypes.GoabFormStorageType;
export type GoabFormOnMountDetail = CommonTypes.GoabFormOnMountDetail;
export type GoabFormOnStateChange = CommonTypes.GoabFormOnStateChange;
export type GoabDrawerPosition = CommonTypes.GoabDrawerPosition;
export type GoabDrawerSizeUnit = CommonTypes.GoabDrawerSizeUnit;
export type GoabDrawerSize = CommonTypes.GoabDrawerSize;

// Generic types
export type GoabInputOnChangeDetail<T = string> = CommonTypes.GoabInputOnChangeDetail<T>;
export type GoabInputOnFocusDetail<T = string> = CommonTypes.GoabInputOnFocusDetail<T>;
export type GoabInputOnBlurDetail<T = string> = CommonTypes.GoabInputOnBlurDetail<T>;
export type GoabInputOnKeyPressDetail<T = string> =
  CommonTypes.GoabInputOnKeyPressDetail<T>;
export type OnChange<T = string> = CommonTypes.OnChange<T>;
export type OnFocus<T = string> = CommonTypes.OnFocus<T>;
export type OnBlur<T = string> = CommonTypes.OnBlur<T>;
export type OnKeyPress<T = string> = CommonTypes.OnKeyPress<T>;
