#!/usr/bin/bash

if [ ! -f .env ]; then cp ./.env.example ./.env; fi

if [ ! -d "./apps/dev" ]; then
  mkdir ./apps/dev
  cp -r ./.templates/* ./apps/dev
fi

# formatting github hook prompt
read -r -p "Enable the format pre-commit git hook? (y/N) " response
if [[ "$response" =~ ^[Yy]$ ]]; then
  cp scripts/pre-commit .git/hooks/pre-commit
  chmod +x .git/hooks/pre-commit
  echo "Pre-commit hook installed."
fi

echo "Dev env created!"
