#!/bin/bash

target=$1

# Ensure local repo is in sync with remote ()
git fetch upstream

if [ ! -n "$target" ]; then
  echo "pg-switch [target] => Target repository is required"
  exit 1
fi

if [ -n "$(git status -s -uno)" ]; then
  echo "Uncommitted changes exist, commit or stash changes before proceeding"
  exit 1
fi

if [ -z "$(git branch | grep "$target")" ]; then
  echo "[$target] is an invalid target branch name"
  exit 1
fi

# Get the current git branch name
branch=$(git branch --show-current)

# Check if branch equals target
if [ "$branch" = "$target" ]; then
  echo "Already on target branch: $target"
  exit 0
fi

# Check if .playgrounds directory exists, create it if it doesn't
if [ ! -d ".playgrounds/$branch" ]; then
    mkdir -p .playgrounds/"$branch"
fi

# Move the existing playground to the .playgrounds dir
if [ -d "playground" ]; then
  mv playground/* .playgrounds/"$branch"
fi

# Move the target playground to the `playground` dir to allow it to tested
targetdir=".playgrounds/$target"
if [ -n "$target" ] && [ -d "$targetdir" ]; then
  cp -r "$targetdir"/* playground
  rm -rf "$targetdir"
else
  cp -r .templates/* playground
fi

# Checkout the defined target repo
git checkout "$target"
