import { CUSTOM_ELEMENTS_SCHEMA, Component } from "@angular/core";
import { CommonModule } from "@angular/common";
import {
  GoabAccordion,
  GoabAppFooter,
  GoabAppFooterMetaSection,
  GoabAppFooterNavSection,
  GoabAppHeader,
  GoabAppHeaderMenu,
  GoabBadge,
  GoabBlock,
  GoabButton,
  GoabButtonGroup,
  GoabCallout,
  GoabCheckbox,
  GoabChip,
  GoabCircularProgress,
  GoabContainer,
  GoabDatePicker,
  GoabDetails,
  GoabDivider,
  GoabDropdown,
  GoabDropdownItem,
  GoabFileUploadCard,
  GoabFileUploadInput,
  GoabFormItem,
  GoabFormStep,
  GoabFormStepper,
  GoabHeroBanner,
  GoabIcon,
  GoabIconButton,
  GoabInput,
  GoabModal,
  GoabNotification,
  GoabPages,
  GoabPagination,
  GoabPopover,
  GoabRadioGroup,
  GoabRadioItem,
  GoabSideMenu,
  GoabSideMenuGroup,
  GoabSideMenuHeading,
  GoabSkeleton,
  GoabTab,
  GoabTable,
  GoabTabs,
  GoabTooltip,
  GoabSpacer,
  GoabTextArea,
} from "@abgov/angular-components";

@Component({
  standalone: true,
  selector: "abgov-component-wrapper",
  template: `
    <div style="width: 1024px; margin: 0 auto;">
      <!-- Test code goes here -->
    </div>
  `,

  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  imports: [
    CommonModule,
    GoabBadge,
    GoabButton,
    GoabDropdown,
    GoabDropdownItem,
    GoabDatePicker,
    GoabModal,
    GoabAccordion,
    GoabAppFooter,
    GoabAppFooterMetaSection,
    GoabAppFooterNavSection,
    GoabAppHeader,
    GoabAppHeaderMenu,
    GoabButtonGroup,
    GoabCallout,
    GoabCheckbox,
    GoabChip,
    GoabContainer,
    GoabDetails,
    GoabDivider,
    GoabFileUploadCard,
    GoabFileUploadInput,
    GoabFormItem,
    GoabFormStep,
    GoabFormStepper,
    GoabPages,
    GoabHeroBanner,
    GoabIcon,
    GoabIconButton,
    GoabInput,
    GoabNotification,
    GoabPagination,
    GoabPopover,
    GoabCircularProgress,
    GoabRadioGroup,
    GoabRadioItem,
    GoabSideMenu,
    GoabSideMenuGroup,
    GoabSideMenuHeading,
    GoabSkeleton,
    GoabTable,
    GoabTabs,
    GoabTab,
    GoabTextArea,
    GoabTooltip,
    GoabBlock,
    GoabSpacer,
  ],
})
export class ComponentWrapperPageComponent {}
