name: Release CI

on:
  push:
    branches:
      - main
      - next
      - dev

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install npm 11
        run: npm install -g npm@11

      - run: npm ci

      - name: Get last successful commit
        uses: nrwl/nx-set-shas@v3
        id: last_successful_commit
        with:
          main-branch-name: ${{ github.ref_name }}

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build:prod

      - name: Test
        run: |
          if [ -d "./dist" ]; then
            npx playwright install --with-deps
            npm run test:pr
          fi

      - name: Update Web components documentation
        run: cp libs/web-components/README.md dist/libs/web-components

      - name: Release libs
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx nx affected --target release --parallel=false --base=${{ steps.last_successful_commit.outputs.base }}

  publishDocs:
    runs-on: ubuntu-latest

    # for now just run on the "doc" branch
    if: github.ref == 'refs/heads/docs'

    needs: build

    environment:
      name: Prod

    steps:
      - name: Oc login
        uses: redhat-actions/oc-login@v1
        with:
          # URL to your OpenShift cluster.
          # Refer to Step 2.
          openshift_server_url: ${{ secrets.ARO_SERVER }}
          openshift_token: ${{ secrets.ARO_TOKEN }}

          # Disables SSL cert checking. Use this if you don't have the certificate authority data.
          insecure_skip_tls_verify: true
          # This method is more secure, if the certificate from Step 4 is available.
          # certificate_authority_data: ${{ secrets.CA_DATA }}

          # Optional - this sets your Kubernetes context's current namespace after logging in.
          namespace: ui-components-build

      - name: Tag Prod
        run: oc tag design-system-docs:latest design-system-docs:prod

      - name: Publish docs
        run: |
          oc project ui-components-prod
          oc rollout latest dc/design-system-docs
